[package]
name = "blinky"
version = "0.1.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arduino_nano33iot = "0.7.0"
panic-halt = "0.2.0"
